version: '3.8'

services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data-teste

    command: [ "redis-server", "--appendonly", "yes" ]

    networks:
      - app-network


  tomcat:
    build: .
    container_name: tomcat
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8


  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - tomcat
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local


